language: python
# Run on Travis CI's docker infrastructure
sudo: false

env:
  # We have to explicitly use the CC arguments here because Travis does not
  # support the compiler directive with language: python.
  - TOXENV=py26 CC=gcc
  - TOXENV=py27 CC=gcc
  - TOXENV=py33 CC=gcc
  - TOXENV=py34 CC=gcc
  - TOXENV=py35 CC=gcc
  - TOXENV=pypy CC=gcc
  - TOXENV=py26 CC=clang
  - TOXENV=py27 CC=clang
  - TOXENV=py33 CC=clang
  - TOXENV=py34 CC=clang
  - TOXENV=py35 CC=clang
  - TOXENV=pypy CC=clang
  - TOXENV=pep8
  - TOXENV=py3pep8

install: .travis/install.sh

script: .travis/run.sh

branches:
  only:
    - master
