language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "PyPy"
install:
  - "pip install ."
script:
  - py.test
branches:
  only:
    - master
matrix:
  allow_failures:
    # Travis-CI currently has PyPy 1.9 which does not have the CFFI backend.
    #   See: https://github.com/travis-ci/travis-ci/issues/1106
    - python: "PyPy"
